### PR TITLE
Removed logging

### PR DESCRIPTION
**Pull request by JasperH8g**
This was bugging me a lot :)

### CODE REVIEW

**Comment by nelsonic** [comment]
@Jpunt we'er happy to remove the console.logs if they're annoying. :wink: 
please increase the version number in `package.json` to `1.0.7` so we can publish the new version. :computer: 
thanks. :+1:

**Comment by JasperH8g** [comment]
@nelsonic done!

**Comment by nelsonic** [comment]
@Jpunt thanks. merged.

**Comment by nelsonic** [comment]
`1.0.7` is on NPM. :+1:

**Pull request merged**
