### PR TITLE
remove console.log

### LINKED ISSUE #5: Remove `console.log`s or expose option to squelch them
This module is great and works perfectly, but it would be nice to have a way to not output to stdout on kill. This has tripped me up while using it to make a command line tool that can be piped into other sources as it disrupts the output. I think that things are usually best to be silent unless something unexpected happens or they are asked to be verbose.

I would be happy to PR the change, but wanted to get your opinion on it as a possibility.

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #5 
You should merge this after my other PRs, it might conflict

### CODE REVIEW

**Comment by nelsonic** [comment]
@jedwards1211 please resolve merge conflict and ping me. thanks! 👍

**Comment by jedwards1211** [comment]
@nelsonic done!

**Comment by nelsonic** [comment]
@jedwards1211 does this PR make any _changes_?

**Comment by jedwards1211** [comment]
ah, looks like not because I moved most stuff including console.log to handlePsTreeCallback for testing.  I'll make a new PR...

**Pull request closed without merging**
