### PR TITLE
Update to latest ps-tree@1.1.1 

### LINKED ISSUE #35: The ps-tree package may be unsafe now. Better find an alternative.
See:
https://github.com/indexzero/ps-tree/issues/33
https://github.com/dominictarr/event-stream/issues/116

### PR DESCRIPTION
**Pull request by nelsonic**
fixes https://github.com/dwyl/terminate/issues/35

### CODE REVIEW

**Review by iteles — APPROVED** [review]
:+1: Thanks for doing this `chore` @nelsonic

**Comment by nelsonic** [comment]
CI failing because of `package-lock.json` incongruity ...
https://travis-ci.org/dwyl/terminate/jobs/459971285#L442
image

🙄

**Comment by nelsonic** [comment]
Works on `localhost`:
image

**Comment by nelsonic** [comment]
I don't "miss" Node.js ... 😞 
image
Why would the tests pass for one version of node and fail for another? 😠

**Pull request merged**
